# TazPod Configuration
version: 1.0

# Final Image
image: "tazzo/tazlab.net:tazpod-gemini"

# Container Settings
container_name: "tazpod-lab"
user: "tazpod"

# Build Settings (Build Gemini layer locally)
build:
  dockerfile: ".tazpod/Dockerfile.gemini"
  context: "."

# Features
features:
  ghost_mode: true
  debug: false