# TazPod Configuration
version: 1.0

# Base Image
image: "tazzo/tazlab.net:tazpod-k8s"

# Container Settings
container_name: "tazpod-lab"
user: "tazpod"

# Build Settings
build:
  dockerfile: ".tazpod/Dockerfile.k8s"
  context: "."

# Features
features:
  ghost_mode: true
  debug: true
